### ISSUE TITLE
TypeScript 2.9 meta-issue

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-TmLanguage#603]
We need to make sure our grammar is ready for

* [x] `import(...)` types (https://github.com/Microsoft/TypeScript/issues/14844)
* [x] Generics on JSX Elements (https://github.com/Microsoft/TypeScript/pull/22415)
* [ ] Generics on Tagged Templates (https://github.com/Microsoft/TypeScript/pull/23430)

**Comment by sheetalkamat** [comment]
Isnt import type done by 4ef3570784b60450d6baac681cb096fbf1d2397e

**Comment by sheetalkamat** [comment]
Generics for JSX is handled by aef7be5c6dafd9f703a59aebd378da97acdf1023
